name: 'Gihub Project Auto'
description: 'Automation of Github projects'
author: 'Jeff Daniel'
inputs:
  github-token:
    description: 'The GitHub token'
    required: false
    default: ${{ github.token }}
  labels-add:
    description: 'Labels to add to an issue, seperated by commas.'
    required: false
  labels-remove:
    description: 'Labels to be removed from an issue, seperated by commas.'
    required: false
  project-scope:
    description: 'Scope of the project search. Values: organization | repository | user | all'
    required: false
  project-name:
    description: 'The name of the GitHub Project'
    required: false
  project-column:
    description: 'The name of the column to move the issue or pull request to'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: fast-forward
  color: purple