name: Test Jeff
on:
  project_card:
    types:
      - moved
  issues:
    types:
      - locked
  pull_request:
    types:
      - locked
jobs:
  moved-to-others:
    if: github.event.project_card.column_id == '14432401' || github.event.project_card.column_id == '14432396'
    runs-on: ubuntu-latest
    steps:
      - name: Remove Label `qa-ready`
        uses: jeffdanielperso/github-project-auto@latest
        with:
          remove-labels: "qa-ready"
  moved-to-in-progress:
    if: github.event.project_card.column_id == '14432400'
    runs-on: ubuntu-latest
    steps:
      - name: Add Label `qa-ready`
        uses: jeffdanielperso/github-project-auto@latest
        with:
          add-labels: "qa-ready"
      - name: Project Orga Board
        uses: jeffdanielperso/github-project-auto@latest
        with:
          project: "Orga Board"
          column: "In progress"
          repo-token: ${{ secrets.GHA_JEFF }}